apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: arvind-db
  name: arvind-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arvind-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: arvind-db
    spec:
      volumes:
      - name: arvind-vol
        persistentVolumeClaim:
         claimName: arvind-pvc
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts: # to mount the volume
        - name: arvind-vol
          mountPath: /data/db/ # mounting in default mongo location
        envFrom:
        - secretRef:
            name: arvind-db-cred
status: {}
