apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: arvind-web-lb
  name: arvind-web-lb
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector: # pod finder using label of pods
    app: arvind-deploy1
  type: ClusterIP
status:
  loadBalancer: {}
