apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: arvind-node
  name: arvind-node-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: arvind-node
  type: LoadBalancer
status:
  loadBalancer: {}
